### ISSUE TITLE
java.lang.NoSuchMethodError in Vaadin 14.8.1

### ISSUE THREAD

**Issue by JariHanah** [appreciated/paper-card#48]
after upgrading Vaadin from 14.7.1 to 14.8.1 i am getting:

java.lang.NoSuchMethodError: org.jsoup.nodes.Element.traverse(Lorg/jsoup/select/NodeVisitor;)Lorg/jsoup/nodes/Element;
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.inspectTwoWayBindings(TemplateDataAnalyzer.java:244) ~[flow-server-2.7.7.jar:2.7.7]
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:233) ~[flow-server-2.7.7.jar:2.7.7]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.lambda$null$23ee5b4f$1(TemplateInitializer.java:91) ~[flow-server-2.7.7.jar:2.7.7]
	at com.vaadin.flow.internal.ReflectionCache.lambda$wrapValueProvider$d0062d93$1(ReflectionCache.java:93) ~[flow-server-2.7.7.jar:2.7.7]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_261]
	at com.vaadin.flow.internal.ReflectionCache.get(ReflectionCache.java:110) ~[flow-server-2.7.7.jar:2.7.7]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:92) ~[flow-server-2.7.7.jar:2.7.7]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:91) ~[flow-server-2.7.7.jar:2.7.7]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:106) ~[flow-server-2.7.7.jar:2.7.7]
	at com.github.appreciated.card.AbstractCard.<init>(AbstractCard.java:22) ~[card-2.0.0.jar:2.0.0]
	at com.github.appreciated.card.Card.<init>(Card.java:19) ~[card-2.0.0.jar:2.0.0]
	at com.alhanah.taqueem.view.cards.CardUtil.getCard(CardUtil.java:17) ~[classes/:na]
